sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: NEc7V0b4XaZfCzk8pne6dLV9wsM036yb9C+rkrXORQJuBHP7k93b5jcXzLvqE1LbZwyoWVroAmOKBR+0+ZoqcfcTU49dL6W3kmdbJr6ltxHHqcJ+9ES7bdxOMxuu7Uy+EQrdKOOfxh6MPOPQC6+d3bAwiMYuzM1yUtif7oYuFMsR7aRqQreWVnpiJPy4+EDOGmEw+WHgr9vms3RsK4dyECbnLYaCBsK0IAzYh94wKz7/NCBYANExojKuvKNBQvonjz/tMW/2y/9MS5+N8il9H/skzkgbB2jkwaC9Ved2m41TCVaPWg1DBLvN/T/bcD3br4a6r71V9QiDxS12qcc/gtlpKKByAiYMu8clhrBgda9PGGxuAAVeJwcAzcw6SMfoAaymSuhZQDfKiHdFBu4cxCjRFL7SkN5ReBRZfRaYfxuN66Lftd3rukwiz3xFX1XlXpqDPQQlgKm0KbLQZro1M3qaRgUc01kp+JLyDElLs/3sgWjJfof2+V5+kNSSoni5W9VOVg7+5ukPxVaGpY40B5nL0T5WcE5U4xrOaoyQsBwuyJSpxdSQ2N2NP7mJ5NyX6zaLAc2MGsIbNftygOWwJIVZ4rCVMp3NP3bc9BDlMHenWINzVpfh3x2Sy1TI8yDgfjYGjMxwGkkXzz8NzvOHFJ35Y4q9T/d0yLXoZS+XupM=
