sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: RtA5YtWkbIlqhVhLsTd5i912ERdHTEOcMPG7I4Kw2wXy2SOjXN/jGM3+VMpvLpv1LxKJOws37tQvSjnFfN/HW3I4paaxDukitX4m3H017YiY2VxjhU7buHX6MBY8wAe/qtRZJbiZ44N5ww0HKyF3t9JrwS6UGaoxDreshRwt4DRBs+YA0V/z/fZoFY5zXpudjUiqgA2bXpDgYcURn2muEEJ5pD07bT+SdMldKFfOi/j6r8Uc1ibmcBxDTZ+42KKwT3NPd28ERVYInMlcepb1OB0N5MzDHE9gAqkCooE9WlZPL4AcXrxajhYpMMLamkTiOHsiBuUmGyBgrn76y4ypiW5gf1dVhz9h7YSBJAw5tGUmPHoG7/yigSTt7rabvFHpko7m372VENOky1kIrrLzaxJNspD0ujRw5ZZVqbxDZflPAE1jUNv/PZlKFze4zHaL8RFns0rv0tq3zNaiUki4TvRtgqxWrkrfPFyEp9WUMFcintB+B9z8kwCbWA/6Jwuby1QOtD7QmmSkEqnroJeahS71n1Z4+xJUk/b6EdOd18ew7PJ3VJMD3pkQddDJ6ly+SIl2SAyIAWOk4YPd+IzCcOm3vIxeHasLnnp/Gs1vTNSfQbgReOcNYm0IMM174HcqtGYf9prGRI3Bjp6B2pGGUipMO+D2V2pSzpSL+SbgBDQ=
  - secure: v5nmXdqD8YvOUFlNRUzeDy73nDDmlSM0SW5jhS/zgWDa2SqLH9SbIGR1LQHKmzhs96GrVFQrPb/GibDKmIYo5FVsXXqzs0YvfDXkMO/ejZIs4k8Td/kLqbRCevK+xovJf3XZ44NwcreCF3jY9XRyasZRi65DK27tri53Ynahv+WGDl4w/3soTGR8xBHDmbE8uwVOL21ybIsFoQNCL4XcfROSVhjbGQQyspLuivkGipFuFa1aPlqnDdCmPBb1SBV7x+GPuDdry2uDdNulW74qXFvN8V5PJGsoJ5LtKeilNIEgTtD796tkpdwhQuBwqFU61G/LyNltGXWQhrntCjErdsHYsOezrVb1X3RUOoOma2Afp/y76WNiEuB06abyhXO5h98Un3dNa7rFiUxK1pcMAsyQnkKbvaJ/Y8TqsPyYEYRSA0gO6ayJeHWRsS6H3IfDlF1H29GIppAIQLC5UwERxFK3iVfEVwX1PX4d/75+QpyL1IPxq1jlVeqivFEom5QCWfYVpM27mmUsv37VcTG3oOOjdJdccuLTkPwp2VSbGpBhzOsiHpn+ffTzIJdGOxd9Adb9PbDETNVPdxF3FLZWd41Zfcmp+M62VNOljry9KT4nX4Hi8Jhv6KskWxYITMpNv1ZMLPJcPXyrbFUmE2bbry4hBJ9nn0ha4DSmjOPT40A=
